package com.proyectos.comidasapp.clases;

//Generated 11/06/2015 16:12:22 by Hibernate Tools 3.4.0.CR1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* Actividad generated by hbm2java
*/
@Entity
@Table(name = "unidad")
public class Unidad implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long idUnidad;
	private String nombre;
	private String abreviatura;
	
	@Id
    @Column(name = "idUnidad")
    @GeneratedValue(strategy = GenerationType.AUTO)
	public long getIdUnidad() {
		return idUnidad;
	}
	public void setIdUnidad(long idUnidad) {
		this.idUnidad = idUnidad;
	}
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getAbreviatura() {
		return abreviatura;
	}
	public void setAbreviatura(String abreviacion) {
		this.abreviatura = abreviacion;
	}	
	
}
	
